/* Generated By:JJTree&JavaCC: Do not edit this line. PointcutExpressionParserConstants.java */
package org.jboss.aop.pointcut.ast;

public interface PointcutExpressionParserConstants {

  int EOF = 0;
  int AND = 3;
  int OR = 4;
  int CALL = 5;
  int ALL = 6;
  int EXECUTION = 7;
  int CONSTRUCTION = 8;
  int HAS = 9;
  int HAS_FIELD = 10;
  int GET = 11;
  int SET = 12;
  int FIELD = 13;
  int WITHIN = 14;
  int WITHINCODE = 15;
  int POINTCUT = 16;
  int POINTCUT_IDENTIFIER = 17;
  int POINTCUT_WILD_LETTER = 18;
  int POINTCUT_DOT = 19;
  int NOT = 20;
  int ALL_PARAMS = 23;
  int PARAM_CLASS = 24;
  int PARAM_ARRAY_CLASS = 25;
  int PARAM_ANNOTATION = 26;
  int PARAM_INSTANCEOF = 27;
  int PARAM_TYPEDEF = 28;
  int PARAM_IDENTIFIER = 29;
  int COMMA = 30;
  int PARAM_WILD_LETTER = 31;
  int PARAM_DOT = 32;
  int PARAM_ARRAY = 33;
  int PARAMS_CLOSE = 34;
  int ABSTRACT = 37;
  int FINAL = 38;
  int PRIVATE = 39;
  int PROTECTED = 40;
  int PUBLIC = 41;
  int STATIC = 42;
  int NATIVE = 43;
  int SYNCHRONIZED = 44;
  int NEW = 45;
  int THROWS = 46;
  int INSTANCEOF = 47;
  int TYPEDEF = 48;
  int CLASS = 49;
  int EXCEPTION_SEPERATOR = 50;
  int ARRAY_CLASS = 51;
  int ANNOTATION = 52;
  int IMPLEMENTS = 53;
  int IMPLEMENTING = 54;
  int IDENTIFIER = 55;
  int WILD_LETTER = 56;
  int DOT = 57;
  int ARRAY = 58;
  int SEPARATOR = 59;
  int BEHAVIOR_NOT = 60;
  int PARAMS_OPEN = 61;
  int BEHAVIOR_CLOSE = 62;
  int FIELD_ABSTRACT = 65;
  int FIELD_FINAL = 66;
  int FIELD_PRIVATE = 67;
  int FIELD_PROTECTED = 68;
  int FIELD_PUBLIC = 69;
  int FIELD_STATIC = 70;
  int FIELD_TRANSIENT = 71;
  int FIELD_NATIVE = 72;
  int FIELD_SYNCHRONIZED = 73;
  int FIELD_INSTANCEOF = 74;
  int FIELD_TYPEDEF = 75;
  int FIELD_CLASS = 76;
  int FIELD_ARRAY_CLASS = 77;
  int FIELD_ANNOTATION = 78;
  int FIELD_IDENTIFIER = 79;
  int FIELD_WILD_LETTER = 80;
  int FIELD_DOT = 81;
  int FIELD_ARRAY = 82;
  int FIELD_SEPARATOR = 83;
  int FIELD_NOT = 84;
  int FIELD_CLOSE = 85;

  int DEFAULT = 0;
  int PARAMS = 1;
  int BEHAVIOR = 2;
  int FIELD_DECLARATION = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<AND>",
    "<OR>",
    "\"call(\"",
    "\"all(\"",
    "\"execution(\"",
    "\"construction(\"",
    "\"has(\"",
    "\"hasfield(\"",
    "\"get(\"",
    "\"set(\"",
    "\"field(\"",
    "\"within(\"",
    "\"withincode(\"",
    "<POINTCUT>",
    "<POINTCUT_IDENTIFIER>",
    "<POINTCUT_WILD_LETTER>",
    "<POINTCUT_DOT>",
    "\"!\"",
    "\" \"",
    "\"\\t\"",
    "\"..\"",
    "<PARAM_CLASS>",
    "<PARAM_ARRAY_CLASS>",
    "<PARAM_ANNOTATION>",
    "<PARAM_INSTANCEOF>",
    "<PARAM_TYPEDEF>",
    "<PARAM_IDENTIFIER>",
    "\",\"",
    "<PARAM_WILD_LETTER>",
    "<PARAM_DOT>",
    "\"[]\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"abstract\"",
    "\"final\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"static\"",
    "\"native\"",
    "\"synchronized\"",
    "\"new\"",
    "\"throws\"",
    "<INSTANCEOF>",
    "<TYPEDEF>",
    "<CLASS>",
    "\",\"",
    "<ARRAY_CLASS>",
    "<ANNOTATION>",
    "<IMPLEMENTS>",
    "<IMPLEMENTING>",
    "<IDENTIFIER>",
    "<WILD_LETTER>",
    "<DOT>",
    "\"[]\"",
    "\"->\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"abstract\"",
    "\"final\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"static\"",
    "\"transient\"",
    "\"native\"",
    "\"synchronized\"",
    "<FIELD_INSTANCEOF>",
    "<FIELD_TYPEDEF>",
    "<FIELD_CLASS>",
    "<FIELD_ARRAY_CLASS>",
    "<FIELD_ANNOTATION>",
    "<FIELD_IDENTIFIER>",
    "<FIELD_WILD_LETTER>",
    "<FIELD_DOT>",
    "\"[]\"",
    "\"->\"",
    "\"!\"",
    "\")\"",
    "\"(\"",
    "\")\"",
  };

}
