/* Generated By:JJTree&JavaCC: Do not edit this line. TypeExpressionParserConstants.java */
package org.jboss.aop.pointcut.ast;

public interface TypeExpressionParserConstants {

  int EOF = 0;
  int AND = 3;
  int OR = 4;
  int HAS = 5;
  int HAS_FIELD = 6;
  int FIELD = 7;
  int CLASS_EXPR = 8;
  int METHOD_EXPR = 9;
  int CONSTRUCTOR_EXPR = 10;
  int NOT = 11;
  int ALL_PARAMS = 14;
  int PARAM_INSTANCEOF = 15;
  int PARAM_TYPEDEF = 16;
  int PARAM_CLASS = 17;
  int PARAM_ARRAY_CLASS = 18;
  int PARAM_ANNOTATION = 19;
  int PARAM_IDENTIFIER = 20;
  int COMMA = 21;
  int PARAM_WILD_LETTER = 22;
  int PARAM_DOT = 23;
  int PARAM_ARRAY = 24;
  int PARAMS_CLOSE = 25;
  int ABSTRACT = 28;
  int FINAL = 29;
  int PRIVATE = 30;
  int PROTECTED = 31;
  int PUBLIC = 32;
  int STATIC = 33;
  int NATIVE = 34;
  int SYNCHRONIZED = 35;
  int NEW = 36;
  int THROWS = 37;
  int INSTANCEOF = 38;
  int TYPEDEF = 39;
  int CLASS = 40;
  int ARRAY_CLASS = 41;
  int ANNOTATION = 42;
  int IDENTIFIER = 43;
  int WILD_LETTER = 44;
  int DOT = 45;
  int EXCEPTION_SEPERATOR = 46;
  int ARRAY = 47;
  int SEPARATOR = 48;
  int BEHAVIOR_NOT = 49;
  int PARAMS_OPEN = 50;
  int BEHAVIOR_CLOSE = 51;
  int FIELD_ABSTRACT = 54;
  int FIELD_FINAL = 55;
  int FIELD_PRIVATE = 56;
  int FIELD_PROTECTED = 57;
  int FIELD_PUBLIC = 58;
  int FIELD_STATIC = 59;
  int FIELD_TRANSIENT = 60;
  int FIELD_NATIVE = 61;
  int FIELD_SYNCHRONIZED = 62;
  int FIELD_INSTANCEOF = 63;
  int FIELD_TYPEDEF = 64;
  int FIELD_CLASS = 65;
  int FIELD_ARRAY_CLASS = 66;
  int FIELD_ANNOTATION = 67;
  int FIELD_IDENTIFIER = 68;
  int FIELD_WILD_LETTER = 69;
  int FIELD_DOT = 70;
  int FIELD_ARRAY = 71;
  int FIELD_SEPARATOR = 72;
  int FIELD_NOT = 73;
  int FIELD_CLOSE = 74;

  int DEFAULT = 0;
  int PARAMS = 1;
  int BEHAVIOR = 2;
  int FIELD_DECLARATION = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<AND>",
    "<OR>",
    "\"has(\"",
    "\"hasfield(\"",
    "\"field(\"",
    "\"class(\"",
    "\"method(\"",
    "\"constructor(\"",
    "\"!\"",
    "\" \"",
    "\"\\t\"",
    "\"..\"",
    "<PARAM_INSTANCEOF>",
    "<PARAM_TYPEDEF>",
    "<PARAM_CLASS>",
    "<PARAM_ARRAY_CLASS>",
    "<PARAM_ANNOTATION>",
    "<PARAM_IDENTIFIER>",
    "\",\"",
    "<PARAM_WILD_LETTER>",
    "<PARAM_DOT>",
    "\"[]\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"abstract\"",
    "\"final\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"static\"",
    "\"native\"",
    "\"synchronized\"",
    "\"new\"",
    "\"throws\"",
    "<INSTANCEOF>",
    "<TYPEDEF>",
    "<CLASS>",
    "<ARRAY_CLASS>",
    "<ANNOTATION>",
    "<IDENTIFIER>",
    "<WILD_LETTER>",
    "<DOT>",
    "\",\"",
    "\"[]\"",
    "\"->\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"abstract\"",
    "\"final\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"static\"",
    "\"transient\"",
    "\"native\"",
    "\"synchronized\"",
    "<FIELD_INSTANCEOF>",
    "<FIELD_TYPEDEF>",
    "<FIELD_CLASS>",
    "<FIELD_ARRAY_CLASS>",
    "<FIELD_ANNOTATION>",
    "<FIELD_IDENTIFIER>",
    "<FIELD_WILD_LETTER>",
    "<FIELD_DOT>",
    "\"[]\"",
    "\"->\"",
    "\"!\"",
    "\")\"",
    "\"(\"",
    "\")\"",
  };

}
